# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Template CI/CD

"on":
  pull_request:
  push:
    branches:
      - master
      - jpa-elide

env:
  JDK_VERSION: 17
  JDK_DISTRIBUTION: 'adopt'
  USER: QubitPi
  EMAIL: jack20220723@gmail.com
  MODEL_PACKAGE_NAME: 'com.qubitpi.ws.jersey.template.models'

jobs:
  mk-yml-style-check:
    uses: QubitPi/hashicorp-aws/.github/workflows/yml-and-md-style-checks.yml@master

  tests:
    name: Unit & Integration Tests
    needs: mk-yml-style-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test environment setup
        uses: ./.github/actions/ci-setup
        with:
          data-models-repo-org: QubitPi
          data-models-repo-name: jersey-webservice-template-jpa-data-models
      - name: Set up Docker for Integration Tests
        uses: docker-practice/actions-setup-docker@master
      - name: Run unit & integration tests
        run: mvn -B clean verify

  documentation:
    name: Test & Release Documentation (including Javadoc)
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test environment setup
        uses: ./.github/actions/ci-setup
        with:
          data-models-repo-org: QubitPi
          data-models-repo-name: jersey-webservice-template-jpa-data-models
      - name: Install dependencies
        working-directory: docs
        run: yarn
      - name: Build documentations
        working-directory: docs
        run: yarn build
      - name: Generate Javadoc
        run: mvn -B clean javadoc:javadoc
      - name: Move Javadoc into documentation directory
        if: github.ref == 'refs/heads/master'
        run: mv target/site/apidocs/ docs/build/apidocs/
      - name: Deploy documentation (including Javadoc) to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          enable_jekyll: false
          user_name: ${{ env.USER }}
          user_email: ${{ env.EMAIL }}

  hashicorp:
    name: Generated Webservice WAR in GitHub Action, and Publish Template AMI Image and Deploy it to EC2 through HashiCorp
    if: ${{ github.event.repository.name != 'jersey-webservice-template' }} # change this to "if: github.ref == 'refs/heads/master'" in fork
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deployment environment setup
        uses: ./.github/actions/cd-setup
        with:
          aws-ws-pkrvars-hcl: ${{ secrets.AWS_WS_PKRVARS_HCL }}
          ssl-certificate: ${{ secrets.SSL_CERTIFICATE }}
          ssl-certificate-key: ${{ secrets.SSL_CERTIFICATE_KEY }}
          nginx-config-file: ${{ secrets.NGINX_CONFIG_FILE }}
          filebeat-config-file: ${{ secrets.FILEBEAT_CONFIG_FILE }}
          aws-ws-tfvars: ${{ secrets.AWS_WS_TFVARS }}
          maven-settings-xml: ${{ secrets.MAVEN_SETTINGS_XML }}
          oauth-properties: ${{ secrets.OAUTH_PROPERTIES }}
          application-properties: ${{ secrets.APPLICATION_PROPERTIES }}
          jpadatastore-properties: ${{ secrets.JPADATASTORE_PROPERTIES }}
          data-models-repo-token: ${{ secrets.DATA_MODELS_PRIVATE_REPO_TOKEN }}
          data-models-repo-org: ${{ secrets.DATA_MODELS_PRIVATE_REPO_ORG }}
          data-models-repo-name: ${{ secrets.DATA_MODELS_PRIVATE_REPO_NAME }}
      - name: Generate webservice WAR file
        run: mvn -B clean package
      - name: Move WAR file to a location for HashiCorp deployment to pickup
        run: mv target/jersey-webservice-template-1.0-SNAPSHOT.war ../hashicorp-aws/hashicorp/webservice/images/
      - name: QubitPi/hashicorp-aws
        uses: QubitPi/hashicorp-aws@master
        with:
          hashicorp-dir: ../hashicorp-aws/hashicorp/webservice
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
